In [25]:
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [26]:
data=pd.read_csv("heart_disease_data.csv")

In [27]:
X=data.drop(columns="target",axis=1)
Y=data["target"]

In [28]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [29]:
print(X.shape,X_train.shape,X_test.shape)

(303, 13) (242, 13) (61, 13)


Logestic Regresion

In [30]:
from sklearn.linear_model import LogisticRegression
model1=LogisticRegression()

In [31]:
model1.fit(X_train,Y_train)

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [37]:
#accuracy on training data
X_train_Prediction=model1.predict(X_train)
training_data_accuracy=accuracy_score(X_train_Prediction,Y_train)
print('Accuracy on Training Data:',training_data_accuracy)

Accuracy on Training Data: 0.8512396694214877


In [39]:
#accuracy on test data
X_test_Prediction=model1.predict(X_test )
test_data_accuracy=accuracy_score(X_test_Prediction,Y_test)
print('Accuracy on Test Data:',test_data_accuracy)

Accuracy on Test Data: 0.819672131147541


In [46]:
# 49,0,0,130,269,0,1,163,0,0,2,0,2
# 46,1,2,150,231,0,1,147,0,3.6,1,0,2
input_data=(52,1,1,134,201,0,1,158,0,0.8,2,1,2)
#change input data to numpy array
data_numpy_array=np.asarray(input_data)
# reshape the numpy array as we are predicting for only on instance

input_data_reshaped=data_numpy_array.reshape(1,-1)
prediction=model1.predict(input_data_reshaped)

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [47]:
prediction

array([1], dtype=int64)

SVM

In [48]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(X_train,Y_train)  

SVC(kernel='linear', random_state=0)

In [49]:
#accuracy on training data
X_train_Prediction=classifier.predict(X_train)
training_data_accuracy=accuracy_score(X_train_Prediction,Y_train)
print('Accuracy on Training Data:',training_data_accuracy)

Accuracy on Training Data: 0.8553719008264463


In [50]:
#accuracy on test data
X_test_Prediction=classifier.predict(X_test )
test_data_accuracy=accuracy_score(X_test_Prediction,Y_test)
print('Accuracy on Test Data:',test_data_accuracy)

Accuracy on Test Data: 0.819672131147541


In [52]:
# 49,0,0,130,269,0,1,163,0,0,2,0,2
# 46,1,2,150,231,0,1,147,0,3.6,1,0,2
input_data=(54,1,0,120,188,0,1,113,0,1.4,1,1,3)
#change input data to numpy array
data_numpy_array=np.asarray(input_data)
# reshape the numpy array as we are predicting for only on instance

input_data_reshaped=data_numpy_array.reshape(1,-1)
prediction=classifier.predict(input_data_reshaped)
prediction

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

Ranodm forest

In [54]:
from sklearn.ensemble import RandomForestClassifier  
classifier2= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier2.fit(X_train,Y_train)  

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [55]:
#accuracy on training data
X_train_Prediction=classifier2.predict(X_train)
training_data_accuracy=accuracy_score(X_train_Prediction,Y_train)
print('Accuracy on Training Data:',training_data_accuracy)

Accuracy on Training Data: 0.987603305785124


In [56]:
#accuracy on test data
X_test_Prediction=classifier2.predict(X_test )
test_data_accuracy=accuracy_score(X_test_Prediction,Y_test)
print('Accuracy on Test Data:',test_data_accuracy)

Accuracy on Test Data: 0.7704918032786885


In [63]:
# 49,0,0,130,269,0,1,163,0,0,2,0,2
# 46,1,2,150,231,0,1,147,0,3.6,1,0,2
input_data=(10,1,1,156,232,0,1,143,0,0,2,0,2)
#change input data to numpy array
data_numpy_array=np.asarray(input_data)
# reshape the numpy array as we are predicting for only on instance

input_data_reshaped=data_numpy_array.reshape(1,-1)
prediction=classifier.predict(input_data_reshaped)
prediction

c:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)